sudo: false
language: python
python:
  - "3.7"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
env:
  matrix:
  - TOXENV=py37-django302
install:
  - pip install -U pip
  - pip install tox
  - pip freeze
script:
  - tox
