language: python
python:
  - "2.7"
env:
  matrix:
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py34-django16
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - pip install tox --use-mirrors
  - pip freeze
script:
  - CI=1 tox
notifications:
  irc:
    channels:
      - "irc.freenode.org#yourlabs"
    template:
      - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
