sudo: false
language: python
python:
  - "2.7"
env:
  matrix:
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py34-django111
install:
  - pip install -U pip
  - pip install tox
  - pip freeze
script:
  - tox
notifications:
  irc:
    channels:
      - "irc.freenode.org#yourlabs"
    template:
      - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
