language: python
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -q -e . --use-mirrors
  - pip install selenium==2.37.2 unittest_data_provider six
before_script:
  - "pep8 --exclude=tests,migrations --ignore=E124,E128 session_security"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - python setup.py test
notifications:
  irc: 
    channels: 
      - "irc.freenode.org#neoskills"
      - "irc.freenode.org#yourlabs"
    template:
      - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
